# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  image: node:16.0.0
  stage: deploy
  script:
    - npm install
    - npx eslint --ext .jsx,.js src
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
